name: Devotion Email Auto Translator

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install google-generativeai

      - name: Run Script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          IMAP_SERVER: "imap.gmail.com"
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python auto_translator.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add meditations/
          git diff-index --quiet HEAD || git commit -m "Feat: 묵상 번역 및 영어 원문 자동 저장"
          git push
